before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: aiOV6T47VUHUyJqPGiGsD8ngbw5FM8oM8iAq5o6IYXaclyUoLLibXfhbSwRXeouZCEI8rIMvUM/abkMDHjO8lL0zE5oUKPwYT2+0lBhhqjkmcCv9NA3ONxG+8CahYMovDqHu/CfgrKVGhmHDo1665Wj+yGtpkJsldS8WpRPKoDLULXSoS6v82mrpxjCg+mLSFyuVlGErs6jRkFzx81YahDrdRFH8Lj9D+haY6NfpFLzyE9bLQbJMpWh/xr8gxo7xvaTg310BAx6Tn3dT6nTrE3hPUMCNYgOXF36W4tMdj+19QlwdISgTBgQc9tkXGIv8kHLFBeMAUlod19bRf3dzplrgJY8LUq6qz792HqMmt7Os3I1NT7cQNyzaimmvD+wqqpsmD8Fo8EP/Wh1bO1ZEw9WKJq8U+7sFey/GmoCk4F3cdLMHl2dVQ6NU7g4FNnRnXKRQGLO9Tqz/0NCNQcXPHrfGGgIWUqy1aJXMGYFdcOBVdL58gs2i9u4rkh8eSX10/wTRpq+W4oaJ6lhQi2e2ta9FQrBQOMwHqWqWI8w2MfrVGUOsJJaAmU3RsVY//EqCymL5rxyy0+Qz+H/Shiton3hs5RuF7OFQ6619thdphNRwRnv0jTzeHAPq2QRCT8+AK/ial6E2wW0m4RjL4eybTRk6parZT3b6d42W74GEyzg= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
